baseURL = "https://carlossucredev.github.io/carlos-learn/"
languageCode = "en"
title = "Carlos Learn"
theme = "github.com/imfing/hextra"

# Opciones de Hextra 
enableRobotsTXT = true
disableKinds = ["RSS"]

[author]
name = "Carlos"
email = "seu@email.com"

[params]
  description = "Blog usando Hugo + Hextra"
  author = "Sucre"
  showDate = true
  showReadingTime = true
  highlightStyle = "monokai"
  darkMode = true

[pagination]
  pagerSize = 10

# --- Navbar ---
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3


